version: 2.1

executors:
  node-docker:
    docker:
      - image: cimg/node:20.12

jobs:
  build-and-push:
    executor: node-docker
    parameters:
      app_dir:
        type: string
      ecr_repo:
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update && sudo apt-get install -y awscli
      - run:
          name: Build Docker image
          command: |
            docker build -f << parameters.app_dir >>/Dockerfile -t << parameters.ecr_repo >>:$CIRCLE_SHA1 .
      - run:
          name: Login to ECR
          command: |
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 197565756669.dkr.ecr.ap-northeast-2.amazonaws.com
      - run:
          name: Push Docker image
          command: |
            docker push << parameters.ecr_repo >>:$CIRCLE_SHA1

workflows:
  version: 2
  build-and-push-all:
    jobs:
      - build-and-push:
          name: build-and-push-chat-ingestor
          app_dir: apps/ws-chat-ingestor
          ecr_repo: 197565756669.dkr.ecr.ap-northeast-2.amazonaws.com/chat-ingestor/fyc-chat-ingestor
      - build-and-push:
          name: build-and-push-chat-persistor
          app_dir: apps/ws-chat-persistor
          ecr_repo: 197565756669.dkr.ecr.ap-northeast-2.amazonaws.com/chat-persistor/fyc-chat-persistor
