version: 2.1
jobs:
  install_pnpm:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install pnpm
          command: |
            export SHELL=/bin/bash
            wget -qO- https://get.pnpm.io/install.sh | ENV="$HOME/.bashrc" SHELL="$(which bash)" bash -
workflows:
  version: 2
  install:
    jobs:
      - install_pnpm
