version: 2.1

executors:
  node-docker:
    docker:
      - image: cimg/node:20.12

jobs:
  build-and-push:
    executor: node-docker
    parameters:
      app_dir:
        type: string
      ecr_repo:
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update && sudo apt-get install -y awscli
      - run:
          name: Build Docker image
          command: |
            docker build -f << parameters.app_dir >>/Dockerfile -t $AWS_ECR_REGISTRY/<< parameters.ecr_repo >>:$CIRCLE_SHA1 .
      - run:
          name: Login to ECR
          command: |
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ECR_REGISTRY
      - run:
          name: Push Docker image
          command: |
            docker push $AWS_ECR_REGISTRY/<< parameters.ecr_repo >>:$CIRCLE_SHA1
      - run:
          name: Write Slack message
          command: |
            echo "✅ *<< parameters.ecr_repo >>* : $AWS_ECR_REGISTRY/<< parameters.ecr_repo >>:$CIRCLE_SHA1 배포 완료" > /tmp/slack_message-<< parameters.ecr_repo >>.txt
      - persist_to_workspace:
          root: /tmp
          paths:
            - slack_message-<< parameters.ecr_repo >>.txt

  slack-notify:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Notify Slack
          command: |
            if [ -z "$SLACK_WEBHOOK_URL" ]; then
              echo "SLACK_WEBHOOK_URL is not set"; exit 1;
            fi
            MSG=$(cat /tmp/slack_message-*.txt | tr '\n' '\\n')
            PAYLOAD="{\"text\":\"$MSG\"}"
            curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" $SLACK_WEBHOOK_URL

workflows:
  version: 2
  build-and-push-all:
    jobs:
      - build-and-push:
          name: build-and-push-chat-ingestor
          app_dir: apps/ws-chat-ingestor
          ecr_repo: chat-ingestor/fyc-chat-ingestor
      - build-and-push:
          name: build-and-push-chat-persistor
          app_dir: apps/ws-chat-persistor
          ecr_repo: chat-persistor/fyc-chat-persistor
      - slack-notify:
          requires:
            - build-and-push-chat-ingestor
            - build-and-push-chat-persistor
