version: 2.1
jobs:
  install_pnpm:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install pnpm
          command: |
            export SHELL=/bin/bash
            curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm
            sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}
workflows:
  version: 2
  install:
    jobs:
      - install_pnpm
