version: 2.1
jobs:
  install_pnpm:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install pnpm
          command: |
            export SHELL=/bin/bash
            curl -L https://get.pnpm.io/v6.16.js | node - add --global pnpm@10.14.0
workflows:
  version: 2
  install:
    jobs:
      - install_pnpm